# Generated by Django 3.1.4 on 2021-01-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={},
            #options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
