# Generated by Django 3.1.4 on 2021-01-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210105_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={},
        ),
    ]
